const qwe = [
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Algorithms",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Source",
      "Junior 1": "- Recursion",
      "Junior 2": "",
      "Junior 3": "- Sorting algorithms (selection sort, insertion sort)",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "- Methods complexity (Big O notation)",
      "Senior 1": "Able to solve complex problems",
      "Senior 2": "- Searching algorithms (binary search tables)",
      "Senior 3": "- Searching algorithms (balanced search trees, hash tables)",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Design and Architecture",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Core design",
      "Junior 1": "- OOP principles",
      "Junior 2": "",
      "Junior 3": "SOLID",
      "Middle 1": "- OOD principles",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Design patterns",
      "Junior 1": "",
      "Junior 2": "Structural: Decorator, Bridge",
      "Junior 3": "Structural: Adapter, Proxy, Composite",
      "Middle 1": "Structural:  Facade",
      "Middle 2": "Structural: Flyweight",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "Creational: Factory Method, Abstract Factory, Singleton",
      "Junior 3": "Behavioral: Strategy",
      "Middle 1": "",
      "Middle 2": "Behavioral:  Interpreter, Observer, Visitor",
      "Middle 3": "Behavioral: Template Method, Chain of Responsibility, Command, Iterator, Mediator, Memento, State",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "Creational: Builder, Prototype",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Other",
      "Junior 1": "MVC",
      "Junior 2": "",
      "Junior 3": "MVVM, Front Controller",
      "Middle 1": "- Clean code",
      "Middle 2": "- Recognize antipatterns and bad practices",
      "Middle 3": "- UML understanding",
      "Senior 1": "Enterprise patterns",
      "Senior 2": "- Layered architecture",
      "Senior 3": "- EDA",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "Inversion of Control, Dependency Injection",
      "Middle 3": "",
      "Senior 1": "- SOA",
      "Senior 2": "",
      "Senior 3": "- Clean Architecture",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "JavaScript Core",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Data types",
      "Junior 2": "- Data type conversion in JS",
      "Junior 3": "- OOP in JS",
      "Middle 1": "- Async/await",
      "Middle 2": "- WebWorkers",
      "Middle 3": "- Proxy",
      "Senior 1": "- Symbols, Typed Arrays",
      "Senior 2": "- Module Loaders, Proxies, Reflect, WeakMap+WeakSet",
      "Senior 3": "- Understands the work of garbage collector",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Scope, context of calling",
      "Junior 2": "- OOP in JS",
      "Junior 3": "",
      "Middle 1": "- ES6: generators and iterators",
      "Middle 2": "- ServiceWorkers",
      "Middle 3": "- ServiceWorkers",
      "Senior 1": "- JSONP",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Hoisting, closure",
      "Junior 2": "- Event loop",
      "Junior 3": "",
      "Middle 1": "- SPA",
      "Middle 2": "- LocalStorage",
      "Middle 3": "- WebStorage, SessionStorage",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Event handling",
      "Junior 2": "- Promises, default parameters, Rest, Spread",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "- RegExp advanced",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- SPA",
      "Junior 2": "- RegExp",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- es6: new types, classes, super, modules, array(object) methods",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "3D",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "Three.JS core concepts",
      "Junior 2": "- BufferAttributes and uniforms",
      "Junior 3": "- material, mesh, geometries",
      "Middle 1": "TypedArrays",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "Analyse and fix performance issues",
      "Senior 2": "Write complex shaders",
      "Senior 3": "GPU computing",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- render loop",
      "Junior 2": "",
      "Junior 3": "Understand GSLS code",
      "Middle 1": "Shadows: Shadow maps, PCF, variance shadows",
      "Middle 2": "- Projections: OrthographicCamera, PerspectiveCamera",
      "Middle 3": "Buffer Geometries",
      "Senior 1": "Understand fill rate bound and vertex bound performance issues",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "Instanced Geometries",
      "Middle 2": "Lights: Diffuse Light, Point Light, ..",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "Textures, Material, MultiMaterial",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "JavaScript Tools",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- jQuery",
      "Junior 2": "- AJAX",
      "Junior 3": "",
      "Middle 1": "- Typescript",
      "Middle 2": "",
      "Middle 3": "- Babel",
      "Senior 1": "- Typescript advanced",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- NPM basics",
      "Junior 2": "- JSON and XML",
      "Junior 3": "",
      "Middle 1": "- State management: \nredux",
      "Middle 2": "",
      "Middle 3": "- Backbone",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "- NPM",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Frameworks",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "React",
      "Junior 1": "React JSX",
      "Junior 2": "Presentation vs Container components",
      "Junior 3": "Forms",
      "Middle 1": "React: HOC, Composition",
      "Middle 2": "React: HOC, Inheritance",
      "Middle 3": "Styling in React",
      "Senior 1": "Performance",
      "Senior 2": "Computing derived Data, reselect, recompose",
      "Senior 3": "React Fiber",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "State vs Props",
      "Junior 2": "Lifecycle",
      "Junior 3": "",
      "Middle 1": "React-redux:Three principles, Actions, Reducers, Store, Provider, Connect",
      "Middle 2": "React-redux: Middlewares",
      "Middle 3": "",
      "Senior 1": "Testing",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "Events",
      "Junior 2": "Refs",
      "Junior 3": "",
      "Middle 1": "Routing in React, react-router",
      "Middle 2": "Async flow in Redux - redux-thunk",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "Data fetching",
      "Junior 2": "Events",
      "Junior 3": "",
      "Middle 1": "React hook",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "Context",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "HTML",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- doctype, DOM",
      "Junior 2": "- HTML basic elements, terminal block elements, multi-purpose block elements",
      "Junior 3": "",
      "Middle 1": "- Frames and iFrames",
      "Middle 2": "- HTML design patterns",
      "Middle 3": "- Web-components",
      "Senior 1": "- Web browser: performance and optimization",
      "Senior 2": "",
      "Senior 3": "- Optimization pages for searching systems",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- HTML code structure",
      "Junior 2": "- forms, input types",
      "Junior 3": "",
      "Middle 1": "- Standards and browser compatibility",
      "Middle 2": "- SVG",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- semantic tag",
      "Junior 2": "- <head> element",
      "Junior 3": "",
      "Middle 1": "- Accessibility in HTML5",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- fonts",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- tables",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Canvas",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- HTML page layouts",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "CSS",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- CSS selectors",
      "Junior 2": "@media",
      "Junior 3": "images optimization",
      "Middle 1": "- BEM",
      "Middle 2": "- CSS preprocesors: variables, nesting",
      "Middle 3": "- Mixins",
      "Senior 1": "- Scalable and modular architecture for CSS",
      "Senior 2": "ability to create any custom css effect (practice https://100dayscss.com/)",
      "Senior 3": "- Preprocessors: advanced using (functions: math, color)",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Elements positioning, floating and layering",
      "Junior 2": "- Selector cascading and inheritance",
      "Junior 3": "- Transitions, animations, transform",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "- PostCSS",
      "Senior 2": "- CSS Modules",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Flexbox",
      "Junior 2": "using fonts in CSS",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Bootstrap 3/4",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- box model",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Mysql Database",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Mysql DDL\n (create, drop, alter)",
      "Junior 2": "",
      "Junior 3": "- Mysql DQL\n (select, show, group by)",
      "Middle 1": "",
      "Middle 2": "- Mysql DML (insert, update, delete)",
      "Middle 3": "- Mysql DQL\n (select, show, joins)",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Version control system (Git)",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "Able to:",
      "Junior 2": "Able to:",
      "Junior 3": "",
      "Middle 1": "Able to use basic git commands through terminal",
      "Middle 2": "Knows the difference between stash, shelve and patch",
      "Middle 3": "Able to reset, revert commits (local and remote, with force push and without)",
      "Senior 1": "Advanced Git logs",
      "Senior 2": "Git prune",
      "Senior 3": "Git LFS",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "commit, update, merge changes from VC",
      "Junior 2": "check out on specific commit",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "Knows the difference between rebase and merge",
      "Middle 3": "",
      "Senior 1": "Git hooks",
      "Senior 2": "",
      "Senior 3": "Git reflog",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "create branch",
      "Junior 2": "knows the difference between pull and fetch",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "Squash commit",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "cherry pick changes on branch from different branches",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "apply patches, revert changes",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Testing, code quality checking",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "- Unit testing concept",
      "Junior 3": "- Writing unit tests on base of chosen tool",
      "Middle 1": "- Regularly reviewing of other's code",
      "Middle 2": "- Choosing and using unit testing tools",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "- Ability to find memory leaks, kept in memory garbage and optimize code to avoid such",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "- F.I.R.S.T principles",
      "Junior 3": "",
      "Middle 1": "- Providing valuable and comprehensive feedback to the author as a result of code review",
      "Middle 2": "- Able to profile code, identify weak points (functions, blocks) and optimize them",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "- Using ESLint",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Debugging",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "Able to debug using DOM breakpoints, conditional breakpoints, logs",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Build  system",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Webpack",
      "Junior 1": "",
      "Junior 2": "Able to setup project",
      "Junior 3": "",
      "Middle 1": "Knows solutions of common\nproblems with project build",
      "Middle 2": "Able to configure webpack",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "Able to choose appropriate tools for build enviroment",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "NPM",
      "Junior 1": "work with package json",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Back-end system",
      "Junior 1": "",
      "Junior 2": "- Knows Gradle basic tasks and how to fix build problems with them",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "- Java Language Basics",
      "Middle 3": "",
      "Senior 1": "Able to debug using breakpoints, conditional breakpoints, tracing, evaluate expressions",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Network",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- HTTP methods (GET, PUT, POST, DELETE)",
      "Junior 2": "- basic understanding of network concepts (IP, URL)",
      "Junior 3": "- Request/response headers, custom headers",
      "Middle 1": "- TCP, UDP, SSL(HTTPS), SSH",
      "Middle 2": "- Cookies",
      "Middle 3": "- XSS (cross site scripting)",
      "Senior 1": "- Dynamic UI routing",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Status codes",
      "Junior 2": "- Status codes",
      "Junior 3": "- REST concept",
      "Middle 1": "- Security best practices",
      "Middle 2": "- HTTP caching",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "- Partial downloading",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "Process methodologies",
      "Junior 1": "",
      "Junior 2": "",
      "Junior 3": "",
      "Middle 1": "",
      "Middle 2": "",
      "Middle 3": "",
      "Senior 1": "",
      "Senior 2": "",
      "Senior 3": "",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    },
    {
      "": "",
      "Junior 1": "- Attend all meetings",
      "Junior 2": "- Understand basics of SCRUM",
      "Junior 3": "",
      "Middle 1": "- Understand Agile",
      "Middle 2": "- Able to define SCRUM roles",
      "Middle 3": "",
      "Senior 1": "- Conduct daily, estimation and other meetings",
      "Senior 2": "- Risk managment",
      "Senior 3": "- Manage team work, define sprint tasks",
      "Solution Developer": "",
      "Seniour Solution Developer": ""
    }
  ]

  export default qwe;